name: Deploy Astro site to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        # Añade las variables de entorno aquí si son necesarias para el build
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_ID: ${{ secrets.AIRTABLE_TABLE_ID }} # O AIRTABLE_TABLE_NAME
        run: npm run build

      - name: Upload build to GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2 # Mantenemos v2 por ahora
        with:
          path: ./dist

  # --- CORREGIDO: 'deploy' ---
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # --- PASO DE DEBUG ELIMINADO (Opcional) ---
      # - name: Debug Context
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       console.log(JSON.stringify(github, null, 2));
      # --- FIN PASO DE DEBUG ---

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # <<< VOLVEMOS A v2